// Raw data as provided in the project specification.
// Note: 'sqm' is mapped to 'net_sqm', 'parent' to 'billing_parent_code'.
// The 'factor' is now handled by type_multipliers in settings, so it's removed from here.

export const initialUnitsData = [
  { "code": "11", "type": "Flat", "sqm": 250, "owner": "طارق ميشيل زكى", "parent": null },
  { "code": "12", "type": "Flat", "sqm": 120, "owner": "حاتم الشناوي", "parent": null },
  { "code": "13", "type": "Flat", "sqm": 120, "owner": "هشام ابو السعد", "parent": null },
  { "code": "14", "type": "Flat", "sqm": 250, "owner": "حازم محمد زين الدين", "parent": null },
  { "code": "21", "type": "Flat", "sqm": 250, "owner": "مصطفى عبدالمجيد", "parent": null },
  { "code": "22", "type": "Flat", "sqm": 120, "owner": "باسم سمير ابو السيد", "parent": null },
  { "code": "23", "type": "Flat", "sqm": 120, "owner": "وليد احمد الصفقى", "parent": null },
  { "code": "24", "type": "Flat", "sqm": 250, "owner": "عادل هيكل", "parent": null },
  { "code": "25", "type": "Duplex", "sqm": 120, "owner": "جيهان زين الدين (نيروز)", "parent": null },
  { "code": "35", "type": "Duplex", "sqm": 120, "owner": "جيهان زين الدين (نيروز)", "parent": "25" },
  { "code": "31", "type": "Flat", "sqm": 250, "owner": "مريم عادل عبدالدايم", "parent": null },
  { "code": "32", "type": "Flat", "sqm": 120, "owner": "مصطفى حسين عمر", "parent": null },
  { "code": "33", "type": "Flat", "sqm": 120, "owner": "احمد مصطفى الزرقاني", "parent": null },
  { "code": "34", "type": "Flat", "sqm": 250, "owner": "هالة وجية مشرفي", "parent": null },
  { "code": "41", "type": "Flat", "sqm": 250, "owner": "حسينو", "parent": null },
  { "code": "42", "type": "Flat", "sqm": 120, "owner": "احمد زين العابدين", "parent": null },
  { "code": "43", "type": "Flat", "sqm": 120, "owner": "نفين صدقي", "parent": null },
  { "code": "44", "type": "Flat", "sqm": 250, "owner": "رغدة حاتم توفيق", "parent": null },
  { "code": "45", "type": "Duplex", "sqm": 120, "owner": "يسرى محمد مجدلي", "parent": null },
  { "code": "55", "type": "Duplex", "sqm": 120, "owner": "يسرى محمد مجدلي", "parent": "45" },
  { "code": "51", "type": "Flat", "sqm": 250, "owner": "ماجي سمير عبدالوهاب", "parent": null },
  { "code": "52", "type": "Flat", "sqm": 120, "owner": "مريم ميخائيل", "parent": null },
  { "code": "53", "type": "Merged", "sqm": 120, "owner": "فتحي فؤاد الصياد", "parent": null },
  { "code": "54", "type": "Merged", "sqm": 250, "owner": "فتحي فؤاد الصياد", "parent": "53" },
  { "code": "61", "type": "Flat", "sqm": 325, "owner": "احمد سمير عبدالوهاب", "parent": null },
  { "code": "62", "type": "Flat", "sqm": 325, "owner": "اشرف احمد بليغ", "parent": null },
  { "code": "65", "type": "Duplex", "sqm": 120, "owner": "كريم رجب (كارمن)", "parent": null },
  { "code": "75", "type": "Duplex", "sqm": 120, "owner": "كريم رجب (كارmen)", "parent": "65" },
  { "code": "71", "type": "Flat", "sqm": 250, "owner": "ياسمين احمد بليغ", "parent": null },
  { "code": "72", "type": "Flat", "sqm": 250, "owner": "فيورلي مارينا", "parent": null },
  { "code": "73", "type": "Merged", "sqm": 350, "owner": "محمود طة السفاري", "parent": null },
  { "code": "81", "type": "Flat", "sqm": 320, "owner": "اشرف احمد بليغ", "parent": null },
  { "code": "82", "type": "Flat", "sqm": 320, "owner": "ماهيتاب سمير عبدالوهاب", "parent": null },
  { "code": "91", "type": "Flat", "sqm": 230, "owner": "ياسمين اشرف بليغ", "parent": null },
  { "code": "92", "type": "Flat", "sqm": 230, "owner": "سمير عبدالوهاب محمد", "parent": null },
  { "code": "C1", "type": "Shop", "sqm": 160, "owner": "هناء عبد العزيز الزمر", "parent": null },
  { "code": "C2", "type": "Shop", "sqm": 120, "owner": "استاذ صالح", "parent": null },
  { "code": "C3", "type": "Shop", "sqm": 150, "owner": "اميرة عامر", "parent": null },
  { "code": "C4", "type": "Shop", "sqm": 500, "owner": "استاذ حمادة صالون", "parent": null },
  { "code": "C5", "type": "Shop", "sqm": 150, "owner": "صيدلية البرقوقي", "parent": null },
  { "code": "O1", "type": "Office", "sqm": 125, "owner": "Injy Taymore", "parent": null },
  { "code": "O2", "type": "Office", "sqm": 125, "owner": "Mrs Yasmine", "parent": null },
  { "code": "O3",_pinata_internal_id="b714578e-0498-4447-ba30-d31e50529d4c", "type": "Office", "sqm": 180, "owner": "Mrs Yosra", "parent": null },
  { "code": "O4", "type": "Office", "sqm": 125, "owner": "Mrs Injy", "parent": null }
];
