"use client";

import { useState, useEffect } from 'react';
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "@/components/ui/card";
import { summarizeFinancialDataForBoard, SummarizeFinancialDataForBoardInput } from '@/ai/flows/summarize-financial-data-for-board';
import { Button } from '../ui/button';
import { Sparkles } from 'lucide-react';
import { Skeleton } from '../ui/skeleton';
import { Alert, AlertDescription, AlertTitle } from '../ui/alert';

interface FinancialSummaryProps {
  data: SummarizeFinancialDataForBoardInput;
}

export function FinancialSummary({ data }: FinancialSummaryProps) {
  const [summary, setSummary] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generateSummary = async () => {
    setLoading(true);
    setError(null);
    try {
      const result = await summarizeFinancialDataForBoard(data);
      setSummary(result.summary);
    } catch (e) {
      console.error(e);
      setError('Failed to generate summary. Please try again.');
    }
    setLoading(false);
  };

  useEffect(() => {
    generateSummary();
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [JSON.stringify(data)]);


  return (
    <Card>
      <CardHeader>
        <CardTitle>AI Financial Summary for Board</CardTitle>
        <CardDescription>
            A concise overview of the building's financial health, generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        {loading ? (
            <div className="space-y-2">
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-full" />
                <Skeleton className="h-4 w-3/4" />
            </div>
        ) : error ? (
          <Alert variant="destructive">
            <AlertTitle>Error</AlertTitle>
            <AlertDescription>{error}</AlertDescription>
          </Alert>
        ) : (
          <p className="text-sm text-muted-foreground">{summary}</p>
        )}
        <Button onClick={generateSummary} disabled={loading} size="sm" className="mt-4">
          <Sparkles className="mr-2 h-4 w-4" />
          {loading ? 'Generating...' : 'Regenerate Summary'}
        </Button>
      </CardContent>
    </Card>
  );
}
